name: Build Prod

on:
    push:
    pull_request:

jobs:
    exploit:
        name: Exploit
        runs-on: ubuntu-latest
        container: devkitpro/devkitppc:latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Exploit
              run: |
                cd ./exploit
                python3 make-sbcm-patch.py -DPROD -j
                cd ..
            - name: Upload Exploit
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: exploit
                  path: ./exploit/sbcm
    payload:
        name: Payloads
        runs-on: ubuntu-latest
        container: devkitpro/devkitppc:latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Payload
              run: |
                cd ./payload
                python3 make-payload.py -DPROD -j
                mv ./binary ./payload
                cd ..
            - name: Upload Payload Files
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: payload
                  path: ./payload/payload
            - name: Upload Payload .ELF Files
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: payload-elf
                  path: ./payload/build
    launcher: 
        name: Launcher
        runs-on: ubuntu-latest
        container: devkitpro/devkitppc:latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Launcher
              run: |
                cd ./launcher
                make
                cd ..
            - name: Upload Launcher
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: launcher
                  path: ./launcher/launcher.dol
        
    stage1:
        name: Stage 1 and 0
        runs-on: ubuntu-latest
        container: devkitpro/devkitppc:latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Stage 1
              run: |
                cd ./stage1
                python3 make-stage1.py -DPROD -j
                cd ..
            - name: Upload Stage 1
              uses: actions/upload-artifact@v4.0.0 
              with:
                  name: stage1
                  path: ./stage1/build/stage1.bin
            - name: Build Stage 0
              run: |
                cd ./patch
                python3 make-patch.py -DPROD -j
                cd ..
            - name: Upload Stage 0
              uses: actions/upload-artifact@v4.0.0
              with:
                  name: stage0
                  path: ./patch/build/*.txt
    package:
        name: Package
        needs: [exploit, payload, stage1]
        runs-on: ubuntu-latest
        container: devkitpro/devkitppc:latest
        steps:
            - uses: actions/download-artifact@v4.1.7
              with:
                  name: exploit
                  path: ./payload/sbcm
            - uses: actions/download-artifact@v4.1.7
              with:
                  name: payload
                  path: ./payload/binary
            - uses: actions/download-artifact@v4.1.7
              with:
                  name: stage1
                  path: ./payload
            - uses: actions/upload-artifact@v4.0.0
              with:
                  name: packaged-payload-prod
                  path: ./payload